version: "3"
services:
  # Selenium Hub (without OpenTelemetry)
  hub:
    image: selenium/hub:latest
    ports:
      - 4444:4444
    networks:
      - selenium-network
    environment:
      - HUB_HOST=hub

  # Selenium Node for Chrome
  chrome:
    image: selenium/node-chromium
    depends_on:
      - hub
    environment:
      - SE_EVENT_BUS_HOST=hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true
      - SE_NODE_MAX_SESSIONS=1
    networks:
      - selenium-network

  # Selenium Node for Firefox
  firefox:
    image: selenium/node-firefox
    depends_on:
      - hub
    environment:
      - SE_EVENT_BUS_HOST=hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    networks:
      - selenium-network

  # Selenium Docker (Test Runner)
  selenium-docker:
    image: guptachal/selenium-docker:latest
    depends_on:
      - chrome
      - firefox
    environment:
      - TEST_SUITE=testng.xml
      - HUB_HOST=hub
    networks:
      - selenium-network

  # Jenkins with Maven installed
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile.jenkins  # Specify custom Jenkins Dockerfile
    image: custom-jenkins-with-maven
    container_name: jenkins
    user: root
    ports:
      - 8092:8080
      - 50000:50000
    volumes:
      - ./volumes/master:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock  # Allow Jenkins to run Docker commands
    networks:
      - selenium-network

networks:
  selenium-network:
    driver: bridge
